path_model: '/home/jchang13/fusion/mmegogesture-fusion/downloads/Model/model_Fusion.pt'
path_args: '/home/jchang13/fusion/mmegogesture-fusion/downloads/Model/args_Fusion.yaml'
path_save: '/home/jchang13/fusion/mmegogesture-fusion/vis_outputs/'
