process:
  folder: 2025May21-1207_Shubo #2025_May_29_12s #2025May29-shubo #2025May26-1811_shubo #2025May21-1207_Shubo #2025May26-1811_shubo #2025May26-1800_justin #2025May26-1811_shubo #2025_May_21
  folder_path: /bigdata/shuboy/mm-egogesture/data_RPI/2025_May_21/${process.folder}/  #2025May21-1200_Justin/   #2025May21-1207_Shubo/
  # 2025May21-1305_Shubo1.6s/
  radar_data_path: ${process.folder_path}radar/
  radar_file_name: #20250529174902
  activity: 
  uD_threshold: 9.5 #9.5 #9.5 # 10 shubo 9 justin
  radar_config_path: "./radar_capture/waveform_configs/xwr68xx_gesture.cfg"  
  subject: 3
  environment: 1
  
  # # # Output directories
  output_dir: /bigdata/shuboy/mm-egogesture/preprocessed_data/Jun2/resized_imgs/
  output_resize_dir: /bigdata/shuboy/mm-egogesture/preprocessed_data/Jun2/resized_data/

  # Processing configuration
  capture_time: 12 #24 #1.6 #


  if_resize_uD: True
  if_resize_img: True
  if_save_img: True
  if_save_uD: True
  if_save_video: True
  if_visualize_segments: True

  min_segment_length: 1.4
  smooth_sigma: 3
  # gesture_gap_thresh: 0.1 #0.03
  max_gap_within: 0.4  # seconds (to fill small internal dips)
  min_gap_between: 0.2  # seconds (to separate distinct gestures)

  gesture_max_len: 1.6 #1.6
  gesture_min_len: 0.6
  center_segment_second: 1.6 
  video_segment_second: 2.667

  # Fixed params
  cam_fps: 30
  uD_width: 512
  uD_height: 128
  img_width: 256
  img_height: 256
  n_uD_fft: 128 
  stft_window_size: 64
  uD_window: hamming # hann  
  overlap_ratio: 0.875 
  plot_scale: 60
  vmax: 40 
  vmin: 0 


sensor:
  select:
  - rad-uD
  - cam-img
  win_cam: 80
  win_rad: 512
  t_snapshot: 2.667
  fps_cam: 30
train:
  n_class: 12
  pretrain: true
  traintest_split: subject-3_4_5
  # batch_size: 16
  # num_workers: 1
model:
  backbone: mobilenet-3D

data_dir: /bigdata/shuboy/mm-egogesture/preprocessed_data/out_distribution_gestures/resized_data/
path_model: /bigdata/shuboy/mm-egogesture/models/models_0512/concat_345_last.pt

result_dir: /bigdata/shuboy/mm-egogesture/results/
# result:
#   path_des: /home/shuboy/Desktop/Gesture_data/des_testonefile.csv
#   path_data: /home/shuboy/Desktop/Gesture_data/paper_data/

transforms:
  t_actual: 1.6
  t_spare: 0.2
  resample_cam: 16
  cropratio_uD: 1.0
  size_rad_D: 256
  size_rad_T: 512
  size_cam: 256
  mean_std:
    rad-uD:
    - 8.209041172527781
    - 6.378100435571438
    rad-uD_Whalf:
    - 11.5463
    - 6.8219
    rad-uD_Wdouble:
    - 5.0373
    - 6.2107
    rad-A:
    - 40.2172
    - 7.3238
    rad-R:
    - 52.2055
    - 4.7976
    rad-D:
    - 46.6549
    - 23.3134
    rad-uD_channel:
    - 7.6703
    - 7.2454
    cam-img:
    - - 0.4348326325416565
      - 0.1744292676448822
    - - 0.43159499764442444
      - 0.1614103764295578
    - - 0.42124682664871216
      - 0.1674143671989441
